### ISSUE TITLE
ClientReturn has no member MBDBReturn

### ISSUE THREAD

**Issue by Treverr** [gkye/TheMovieDatabaseSwiftWrapper#14]
When using your Wiki code

```
        DiscoverMDB.discover(apiKey, discoverType: "tv", language: nil){
            apiReturn in
            let tvshows = apiReturn.MBDBReturn as! [TVMDB]
            print(tvshows[0].name)
            print(tvshows[0].overview)
            print(tvshows[0].popularity)
        }
```

I get that ClientReturn has no member MBDBReturn?

**Comment by gkye** [comment]
The wiki is outdated since updating to `swift3` i will update them soon. 
Since discover can return both a movie or tv results you will have to initialize the array manual. 

``` swift
    DiscoverMDB.discover("key", discoverType: "tv", language: nil){
      apiReturn in
      let tvshows = TVMDB(results: apiReturn.json!["results"][0])
      dump(tvshows)
    }
```

or you could you use 

``` swift
    DiscoverTVMDB.discoverTV("", first_air_date_year: nil, first_air_date_gte: nil, first_air_date_lte: nil, air_date_gte: nil, air_date_lte: nil, language: "en", sort_by: nil, page: 1, timezone: nil){
      let shows = $0.1
    }
```

If you want specific tv results you could use the functions available in `TVMDB` 

They seems to be an issue with using the default parameters as stated in https://github.com/gkye/TheMovieDatabaseSwiftWrapper/issues/13 i will look into it an fix it soon

**Comment by Treverr** [comment]
How can I access different pages? If i attempt to use another method it sends me the error in #13

**Comment by gkye** [comment]
I'm currently working on an update and also updating the wiki's, it should be completed in an hour or so.

**Comment by Treverr** [comment]
Oh ok! Thank you!

**Comment by gkye** [comment]
ver 0.2.2 has been release if you're using CocoaPods you can update the pod by using `pod update`. The wiki's have also been updates to reflect the recent changes
